### ISSUE TITLE
[Question] Blog On Index.html Not Showing & 404 Blogposts

### ISSUE THREAD

**Issue by grravity** [LukeSmithxyz/lb#43]
I'm trying to get the blog to show on my main index.html (not blogindex.html), they show up on blogindex.html.

I put the <! -- LB -- > where it should post the blogposts.

I think it is related to where lb is, I have /var/www/mysite/ as the root dir, then I cloned lb, so it made an lb folder in /mysite/.

I was having issues with my stylesheet not applying properly to the blogindex.html, so I moved blogindex.html out of lb and put it right in the root dir, and I changed blogindex dir in the lb script to the root folder.

Now, I don't know if the dir placement is the issue, because blogindex.html is in the root dir, as is index.html, however the blog only posts to blogindex, but not index, idky.

The other issue I am having, is for some reason when I make a new blogpost, and it posts onto blogindex, if I go to click the blogpost on the site, it brings me to a 404 page.
If it can post to blogindex, I fail to see why it would be having an issue.

I've never done this before, so maybe I should have my directories different. Not sure. I was considering just moving all files out of lb/, but that'd make my site root dir a mess.

Would really appreciate some support. Thanks.

**Comment by LukeSmithxyz** [comment]
The blogindex files are all just examples. The intended use of the script is that in your root web directory you can just link to wherever the `lb` script is and run it by `./lb`.

If you want to move or rename files, you have to change the variables on top of the `lb` script to their locations relative from where you're running them.

Note also that blog posts do not get automatically posted to any other pages other than the blogindex and the rolling blog page which by default is at `2020.html` (or whatever year it is). Do you not have a file like that? Depending on what you're clicking on that might be your 404.

You can rename the `blogfile` variable to whatever. It's the year by default because I was worried the page would get too big as years went on.
